### ISSUE TITLE
Roadmap for 1.0.0 

### ISSUE THREAD

**Issue by Rheydskey** [Rheydskey/OpenCloud#83]
Roadmap for 1.0.0
===

+ [ ] Create Desktop Client (With [Iced](https://github.com/hecrj/iced))

+ [ ] Finish Mobile App ([Repo](https://github.com/opencloud-rs/opencloud-flutter))

+ [x] Add Support of MySql / Postgre ([Datagn](https://github.com/Rheydskey/datagn))

+ [x] Add Cargo feature for lightweight binaries (#69)
